owl_inverse_of('http://purl.org/datanode/ns/optimizedFrom','http://purl.org/datanode/ns/optimizedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/optimizedFrom','http://purl.org/datanode/ns/processedFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/optimizedFrom','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointPortionWith','http://purl.org/datanode/ns/disjointPartWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointPortionWith','http://purl.org/datanode/ns/differentPopulationFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/links','http://purl.org/datanode/ns/references').
rdfs_sub_property_of('http://purl.org/datanode/ns/links','http://purl.org/datanode/ns/overlappingPopulationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasChange','http://purl.org/datanode/ns/hasUpdate').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasComputation','http://purl.org/datanode/ns/processedInto').
owl_inverse_of('http://purl.org/datanode/ns/isPartOf','http://purl.org/datanode/ns/hasPart').
rdfs_sub_property_of('http://purl.org/datanode/ns/isPartOf','http://purl.org/datanode/ns/overlappingPopulationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasDatatypes','http://purl.org/datanode/ns/hasVocabulary').
owl_inverse_of('http://purl.org/datanode/ns/metadata','http://purl.org/datanode/ns/about').
rdfs_sub_property_of('http://purl.org/datanode/ns/metadata','http://purl.org/datanode/ns/relatedWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasInference','http://purl.org/datanode/ns/hasInterpretation').
owl_inverse_of('http://purl.org/datanode/ns/datatypesOf','http://purl.org/datanode/ns/hasDatatypes').
rdfs_sub_property_of('http://purl.org/datanode/ns/datatypesOf','http://purl.org/datanode/ns/isVocabularyOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/adjacentTo','http://purl.org/datanode/ns/relatedWith').
owl_inverse_of('http://purl.org/datanode/ns/isUpdatedVersionOf','http://purl.org/datanode/ns/hasUpdatedVersion').
rdfs_sub_property_of('http://purl.org/datanode/ns/isUpdatedVersionOf','http://purl.org/datanode/ns/nextVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isUpdatedVersionOf','http://purl.org/datanode/ns/isUpdateOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isDerivationOf','http://purl.org/datanode/ns/relatedWith').
owl_inverse_of('http://purl.org/datanode/ns/previousVersionOf','http://purl.org/datanode/ns/nextVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/previousVersionOf','http://purl.org/datanode/ns/olderVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasDependency','http://purl.org/datanode/ns/references').
rdfs_sub_property_of('http://purl.org/datanode/ns/isUpdateOf','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/isUpdateOf','http://purl.org/datanode/ns/hasUpdate').
rdfs_sub_property_of('http://purl.org/datanode/ns/references','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/processedFrom','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/processedFrom','http://purl.org/datanode/ns/isDerivationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasTypes','http://purl.org/datanode/ns/hasVocabulary').
rdfs_sub_property_of('http://purl.org/datanode/ns/refactoredInto','http://purl.org/datanode/ns/processedInto').
owl_inverse_of('http://purl.org/datanode/ns/isSelectionOf','http://purl.org/datanode/ns/hasSelection').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSelectionOf','http://purl.org/datanode/ns/isPartOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSelectionOf','http://purl.org/datanode/ns/isDerivationOf').
owl_inverse_of('http://purl.org/datanode/ns/isCacheOf','http://purl.org/datanode/ns/hasCache').
rdfs_sub_property_of('http://purl.org/datanode/ns/isCacheOf','http://purl.org/datanode/ns/isSnapshotOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isCacheOf','http://purl.org/datanode/ns/isStandInOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSelection','http://purl.org/datanode/ns/hasDerivation').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSelection','http://purl.org/datanode/ns/hasPart').
owl_inverse_of('http://purl.org/datanode/ns/typesOf','http://purl.org/datanode/ns/hasTypes').
rdfs_sub_property_of('http://purl.org/datanode/ns/typesOf','http://purl.org/datanode/ns/isVocabularyOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasCopy','http://purl.org/datanode/ns/hasDerivation').
owl_inverse_of('http://purl.org/datanode/ns/isExtractionOf','http://purl.org/datanode/ns/hasExtraction').
rdfs_sub_property_of('http://purl.org/datanode/ns/isExtractionOf','http://purl.org/datanode/ns/isInterpretationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasIdentifiers','http://purl.org/datanode/ns/hasSection').
rdfs_sub_property_of('http://purl.org/datanode/ns/attachedTo','http://purl.org/datanode/ns/adjacentTo').
owl_inverse_of('http://purl.org/datanode/ns/attachedTo','http://purl.org/datanode/ns/hasAttached').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAttached','http://purl.org/datanode/ns/adjacentTo').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointCapabilityWith','http://purl.org/datanode/ns/differentVocabularyFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointCapabilityWith','http://purl.org/datanode/ns/differentPopulationFrom').
owl_inverse_of('http://purl.org/datanode/ns/isStatisticOf','http://purl.org/datanode/ns/hasStatistic').
rdfs_sub_property_of('http://purl.org/datanode/ns/isStatisticOf','http://purl.org/datanode/ns/describes').
rdfs_sub_property_of('http://purl.org/datanode/ns/isStatisticOf','http://purl.org/datanode/ns/isComputationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/inconsistentWith','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/isSectionOf','http://purl.org/datanode/ns/hasSection').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSectionOf','http://purl.org/datanode/ns/isPartOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isPortionOf','http://purl.org/datanode/ns/isPartOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSnapshot','http://purl.org/datanode/ns/versionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSnapshot','http://purl.org/datanode/ns/hasCopy').
owl_inverse_of('http://purl.org/datanode/ns/isAdditionOf','http://purl.org/datanode/ns/hasAddition').
rdfs_sub_property_of('http://purl.org/datanode/ns/isAdditionOf','http://purl.org/datanode/ns/isChangeOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasStatistic','http://purl.org/datanode/ns/describedBy').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasStatistic','http://purl.org/datanode/ns/hasComputation').
owl_inverse_of('http://purl.org/datanode/ns/isCopyOf','http://purl.org/datanode/ns/hasCopy').
rdfs_sub_property_of('http://purl.org/datanode/ns/isCopyOf','http://purl.org/datanode/ns/isDerivationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/overlappingVocabularyWith','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/overlappingVocabularyWith','http://purl.org/datanode/ns/sharesInterpretationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/redundantWith','http://purl.org/datanode/ns/overlappingPopulationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/redundantWith','http://purl.org/datanode/ns/overlappingVocabularyWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAttributes','http://purl.org/datanode/ns/hasDescriptors').
rdfs_sub_property_of('http://purl.org/datanode/ns/processedInto','http://purl.org/datanode/ns/hasDerivation').
rdfs_sub_property_of('http://purl.org/datanode/ns/samePopulationAs','http://purl.org/datanode/ns/overlappingPopulationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAddition','http://purl.org/datanode/ns/hasChange').
rdfs_sub_property_of('http://purl.org/datanode/ns/consistentWith','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/cleanedFrom','http://purl.org/datanode/ns/cleanedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/cleanedFrom','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/cleanedFrom','http://purl.org/datanode/ns/processedFrom').
owl_inverse_of('http://purl.org/datanode/ns/isSnapshotOf','http://purl.org/datanode/ns/hasSnapshot').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSnapshotOf','http://purl.org/datanode/ns/versionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSnapshotOf','http://purl.org/datanode/ns/isCopyOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/usesSchema','http://purl.org/datanode/ns/references').
owl_inverse_of('http://purl.org/datanode/ns/relationsOf','http://purl.org/datanode/ns/hasRelations').
rdfs_sub_property_of('http://purl.org/datanode/ns/relationsOf','http://purl.org/datanode/ns/descriptorsOf').
owl_inverse_of('http://purl.org/datanode/ns/isStandInOf','http://purl.org/datanode/ns/hasStandIn').
rdfs_sub_property_of('http://purl.org/datanode/ns/isStandInOf','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/isStandInOf','http://purl.org/datanode/ns/isDerivationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/versionOf','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/schemaUsedBy','http://purl.org/datanode/ns/referencedBy').
owl_inverse_of('http://purl.org/datanode/ns/schemaUsedBy','http://purl.org/datanode/ns/usesSchema').
rdfs_sub_property_of('http://purl.org/datanode/ns/sharesInterpretationWith','http://purl.org/datanode/ns/relatedWith').
owl_inverse_of('http://purl.org/datanode/ns/isExampleOf','http://purl.org/datanode/ns/hasExample').
rdfs_sub_property_of('http://purl.org/datanode/ns/isExampleOf','http://purl.org/datanode/ns/isSelectionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasRelations','http://purl.org/datanode/ns/hasDescriptors').
rdfs_sub_property_of('http://purl.org/datanode/ns/newerVersionOf','http://purl.org/datanode/ns/versionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/optimizedInto','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/optimizedInto','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAnonymized','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAnonymized','http://purl.org/datanode/ns/hasStandIn').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasPart','http://purl.org/datanode/ns/overlappingPopulationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAnnotation','http://purl.org/datanode/ns/metadata').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasAnnotation','http://purl.org/datanode/ns/hasAttached').
rdfs_sub_property_of('http://purl.org/datanode/ns/referencedBy','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/referencedBy','http://purl.org/datanode/ns/references').
owl_inverse_of('http://purl.org/datanode/ns/isSummarizationOf','http://purl.org/datanode/ns/hasSummarization').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSummarizationOf','http://purl.org/datanode/ns/isDerivationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasReification','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSummarization','http://purl.org/datanode/ns/hasDerivation').
rdfs_sub_property_of('http://purl.org/datanode/ns/differentVocabularyFrom','http://purl.org/datanode/ns/differentCapabilityFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasDescriptors','http://purl.org/datanode/ns/hasVocabulary').
rdfs_sub_property_of('http://purl.org/datanode/ns/cleanedInto','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/cleanedInto','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSample','http://purl.org/datanode/ns/hasPortion').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasUpdate','http://purl.org/datanode/ns/sharesInterpretationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasExample','http://purl.org/datanode/ns/hasSelection').
rdfs_sub_property_of('http://purl.org/datanode/ns/sameCapabilityAs','http://purl.org/datanode/ns/sameVocabularyAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/sameCapabilityAs','http://purl.org/datanode/ns/samePopulationAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasUpdatedVersion','http://purl.org/datanode/ns/previousVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasUpdatedVersion','http://purl.org/datanode/ns/hasUpdate').
rdfs_sub_property_of('http://purl.org/datanode/ns/isSampleOf','http://purl.org/datanode/ns/isPortionOf').
owl_inverse_of('http://purl.org/datanode/ns/isSampleOf','http://purl.org/datanode/ns/hasSample').
owl_inverse_of('http://purl.org/datanode/ns/isInferenceOf','http://purl.org/datanode/ns/hasInference').
rdfs_sub_property_of('http://purl.org/datanode/ns/isInferenceOf','http://purl.org/datanode/ns/isInterpretationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/overlappingCapabilityWith','http://purl.org/datanode/ns/relatedWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/differentPopulationFrom','http://purl.org/datanode/ns/differentCapabilityFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/overlappingPopulationWith','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/overlappingPopulationWith','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/isAnonymizedOf','http://purl.org/datanode/ns/hasAnonymized').
rdfs_sub_property_of('http://purl.org/datanode/ns/isAnonymizedOf','http://purl.org/datanode/ns/processedFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/isAnonymizedOf','http://purl.org/datanode/ns/isStandInOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/sameVocabularyAs','http://purl.org/datanode/ns/overlappingVocabularyWith').
owl_inverse_of('http://purl.org/datanode/ns/isAnnotationOf','http://purl.org/datanode/ns/hasAnnotation').
rdfs_sub_property_of('http://purl.org/datanode/ns/isAnnotationOf','http://purl.org/datanode/ns/about').
rdfs_sub_property_of('http://purl.org/datanode/ns/isAnnotationOf','http://purl.org/datanode/ns/attachedTo').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointSectionWith','http://purl.org/datanode/ns/disjointPartWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointSectionWith','http://purl.org/datanode/ns/differentVocabularyFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/isVocabularyOf','http://purl.org/datanode/ns/sharesInterpretationWith').
owl_inverse_of('http://purl.org/datanode/ns/isVocabularyOf','http://purl.org/datanode/ns/hasVocabulary').
rdfs_sub_property_of('http://purl.org/datanode/ns/combinedIn','http://purl.org/datanode/ns/hasDerivation').
owl_inverse_of('http://purl.org/datanode/ns/descriptorsOf','http://purl.org/datanode/ns/hasDescriptors').
rdfs_sub_property_of('http://purl.org/datanode/ns/descriptorsOf','http://purl.org/datanode/ns/isVocabularyOf').
owl_inverse_of('http://purl.org/datanode/ns/isDeletionOf','http://purl.org/datanode/ns/hasDeletion').
rdfs_sub_property_of('http://purl.org/datanode/ns/isDeletionOf','http://purl.org/datanode/ns/isChangeOf').
owl_inverse_of('http://purl.org/datanode/ns/hasPortion','http://purl.org/datanode/ns/isPortionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasPortion','http://purl.org/datanode/ns/hasPart').
owl_inverse_of('http://purl.org/datanode/ns/olderVersionOf','http://purl.org/datanode/ns/newerVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/olderVersionOf','http://purl.org/datanode/ns/versionOf').
owl_inverse_of('http://purl.org/datanode/ns/describedBy','http://purl.org/datanode/ns/describes').
rdfs_sub_property_of('http://purl.org/datanode/ns/describedBy','http://purl.org/datanode/ns/metadata').
rdfs_sub_property_of('http://purl.org/datanode/ns/disjointPartWith','http://purl.org/datanode/ns/adjacentTo').
owl_inverse_of('http://purl.org/datanode/ns/isComputationOf','http://purl.org/datanode/ns/hasComputation').
rdfs_sub_property_of('http://purl.org/datanode/ns/isComputationOf','http://purl.org/datanode/ns/processedFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/remodelledTo','http://purl.org/datanode/ns/processedInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/remodelledTo','http://purl.org/datanode/ns/samePopulationAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasExtraction','http://purl.org/datanode/ns/hasInterpretation').
owl_inverse_of('http://purl.org/datanode/ns/attributesOf','http://purl.org/datanode/ns/hasAttributes').
rdfs_sub_property_of('http://purl.org/datanode/ns/attributesOf','http://purl.org/datanode/ns/descriptorsOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/describes','http://purl.org/datanode/ns/about').
owl_inverse_of('http://purl.org/datanode/ns/hasDerivation','http://purl.org/datanode/ns/isDerivationOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasDerivation','http://purl.org/datanode/ns/relatedWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/remodelledFrom','http://purl.org/datanode/ns/processedFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/remodelledFrom','http://purl.org/datanode/ns/samePopulationAs').
owl_inverse_of('http://purl.org/datanode/ns/remodelledFrom','http://purl.org/datanode/ns/remodelledTo').
rdfs_sub_property_of('http://purl.org/datanode/ns/nextVersionOf','http://purl.org/datanode/ns/newerVersionOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/combinationFrom','http://purl.org/datanode/ns/isDerivationOf').
owl_inverse_of('http://purl.org/datanode/ns/combinationFrom','http://purl.org/datanode/ns/combinedIn').
rdfs_sub_property_of('http://purl.org/datanode/ns/differentCapabilityFrom','http://purl.org/datanode/ns/relatedWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasDeletion','http://purl.org/datanode/ns/hasChange').
rdfs_sub_property_of('http://purl.org/datanode/ns/isInterpretationOf','http://purl.org/datanode/ns/isDerivationOf').
owl_inverse_of('http://purl.org/datanode/ns/isInterpretationOf','http://purl.org/datanode/ns/hasInterpretation').
rdfs_sub_property_of('http://purl.org/datanode/ns/refactoredFrom','http://purl.org/datanode/ns/processedFrom').
owl_inverse_of('http://purl.org/datanode/ns/refactoredFrom','http://purl.org/datanode/ns/refactoredInto').
rdfs_sub_property_of('http://purl.org/datanode/ns/about','http://purl.org/datanode/ns/relatedWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/identifiersOf','http://purl.org/datanode/ns/isSectionOf').
owl_inverse_of('http://purl.org/datanode/ns/identifiersOf','http://purl.org/datanode/ns/hasIdentifiers').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasStandIn','http://purl.org/datanode/ns/overlappingCapabilityWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasStandIn','http://purl.org/datanode/ns/hasDerivation').
owl_inverse_of('http://purl.org/datanode/ns/isDependencyOf','http://purl.org/datanode/ns/hasDependency').
rdfs_sub_property_of('http://purl.org/datanode/ns/isDependencyOf','http://purl.org/datanode/ns/referencedBy').
owl_inverse_of('http://purl.org/datanode/ns/isReificationOf','http://purl.org/datanode/ns/hasReification').
rdfs_sub_property_of('http://purl.org/datanode/ns/isReificationOf','http://purl.org/datanode/ns/processedFrom').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasCache','http://purl.org/datanode/ns/hasSnapshot').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasCache','http://purl.org/datanode/ns/hasStandIn').
owl_inverse_of('http://purl.org/datanode/ns/linkedBy','http://purl.org/datanode/ns/links').
rdfs_sub_property_of('http://purl.org/datanode/ns/linkedBy','http://purl.org/datanode/ns/referencedBy').
rdfs_sub_property_of('http://purl.org/datanode/ns/linkedBy','http://purl.org/datanode/ns/overlappingPopulationWith').
owl_inverse_of('http://purl.org/datanode/ns/isChangeOf','http://purl.org/datanode/ns/hasChange').
rdfs_sub_property_of('http://purl.org/datanode/ns/isChangeOf','http://purl.org/datanode/ns/isUpdateOf').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasVocabulary','http://purl.org/datanode/ns/sharesInterpretationWith').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasSection','http://purl.org/datanode/ns/hasPart').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasInterpretation','http://purl.org/datanode/ns/hasDerivation').
rdfs_sub_property_of('http://purl.org/datanode/ns/sameIdentityAs','http://purl.org/datanode/ns/sameCapabilityAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasCopy','http://purl.org/datanode/ns/sameIdentityAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/isCopyOf','http://purl.org/datanode/ns/sameIdentityAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/duplicate','http://purl.org/datanode/ns/sameIdentityAs').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasChange','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/isChangeOf','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasVocabulary','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/isVocabularyOf','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/hasPart','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/isPartOf','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/sameIdentityAs','http://purl.org/datanode/ns/touch').
rdfs_sub_property_of('http://purl.org/datanode/ns/touch','http://purl.org/datanode/ns/sharesInterpretationWith').
